### PR TITLE
#80 Fixes community-delegated progress bar

### LINKED ISSUE #80: Fix: Community site - Delegation Graph
The delegation graph in the node profile sections doesn't seem to work properly.
It shows the "available for delegation" data correctly but doesn't show "self-delegated" and "community-delegated" values.

Delegation Graph

Example: https://community.taraxa.io/delegation/1072

### PR DESCRIPTION
**Pull request by farebord**
Fixes #80 
Removed bad curly brace.

### CODE REVIEW

File: services/community-site/src/pages/Delegation/NodeProfilePage.tsx [hunk 1]
```diff
@@ -110,6 +110,10 @@ const NodeProfilePage = () => {
     (((node?.totalDelegation || 0) - (node?.ownDelegation || 0)) / delegationPossible) * 100;
   const selfDelegated = ((node?.ownDelegation || 0) / delegationPossible) * 100;
   const availableDelegation = ((node?.remainingDelegation || 0) / delegationPossible) * 100;
+
+  // eslint-disable-next-line no-console
+  console.log(communityDelegated, selfDelegated, availableDelegation);
```
Comment (rattrap) [inline services/community-site/src/pages/Delegation/NodeProfilePage.tsx:115]: Should remove this

**Review by rattrap — CHANGES_REQUESTED** [review]

**Comment by rattrap** [comment]
Let's also show values <= 1% to be 1%
