### PR TITLE
#126 profile breaking fix

### LINKED ISSUE #126: Fix: Community site - Profile page breaks
The profile page breaks if you access it directly - https://qa.community.taraxa.io/profile

Probably because we call a contract before it everything was initialised.

### PR DESCRIPTION
**Pull request by farebord**
Fixes #126

### CODE REVIEW

File: services/community-site/src/pages/Profile/ViewProfile.tsx [hunk 1]
```diff
@@ -101,7 +100,7 @@ function ViewProfileDetails({ points, openEditProfile, openKYCModal }: ViewProfi
   useEffect(() => {
```
Comment (VargaElod23) [inline services/community-site/src/pages/Profile/ViewProfile.tsx:100]: Maybe here instead of calling it with the old account, we could introduce a new useEffect.
```suggestion
  useEffect(() => {
  if(checksumAccount)
  ...
  }, [checksumAccount])
```
And then use the chsckAccount as dep

File: services/community-site/src/pages/Profile/ViewProfile.tsx [hunk 2]
```diff
@@ -90,7 +90,6 @@ interface ViewProfileDetailsProps {
 function ViewProfileDetails({ points, openEditProfile, openKYCModal }: ViewProfileDetailsProps) {
   const auth = useAuth();
   const { account } = useCMetamask();
-  const checksumAccount = ethers.utils.getAddress(account || '');
```
Comment (VargaElod23) [inline services/community-site/src/pages/Profile/ViewProfile.tsx:93]: const [checksumAccount, setChckAccount] =  useEffect<string>(account);

File: services/community-site/src/pages/Profile/ViewProfile.tsx [hunk 3]
```diff
@@ -90,7 +90,6 @@ interface ViewProfileDetailsProps {
...
   const history = useHistory();
   const claimApi = useClaimApi();
   const [lockedPoints, setLockedPoints] = useState(false);
```
Comment (VargaElod23) [inline services/community-site/src/pages/Profile/ViewProfile.tsx:95]: useEffect(() => {
 if(ethers && ethers.utils){
 setChckAccount(ethers.utils.getAddress(account))
}, [account])
})

**Review by VargaElod23 — CHANGES_REQUESTED** [review]
Suggestions submitted.

**Review by VargaElod23 — APPROVED** [review]
LGTM
